### ISSUE TITLE
Реализация БД

### ISSUE THREAD

**Issue by senya-g** [bmstu-iu9/utp2018-1-chat#21]
Можно ли использовать полноценные базы данных (MySQL/MongoDB)?

**Comment by senya-g** [comment]
@alex-qrcs, @Mazdaywik, можно ли использовать полноценные базы данных?

**Comment by Mazdaywik** [comment]
Вообще, базы данных — это курсовой проект весны третьего курса. Но если вы сейчас с ними разберётесь, будет очень неплохо.
