### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by senya-g** [bmstu-iu9/utp2018-1-chat#27]
Здравствуйте!
Нам очень нужна страничка репозитория на GitHub Pages, поэтому я прошу вас предоставить возможность использовать Pages.

На ней будет размещена документация по API и другая информация по работе с приложением.
Конечно, есть Wiki, но для подробного описания API нам показалось это не очень удобно.

Страничка для GitHub Pages будет находиться в отдельной папке `/docs`.
Для этого нам нужна эта настройка:
![image](https://user-images.githubusercontent.com/29691143/43996154-72cbee80-9dc5-11e8-83ae-16c08c9266f8.png)

В `master` папки `/docs` пока нет, но я создал pull request для нее и назначил на него вас.

**Comment by Mazdaywik** [comment]
Теперь вам нужно положить `README.md` в папку `/docs`. А вообще, стоило это сделать сразу в #28.

**Comment by Mazdaywik** [comment]
Потому что без `README.md` или `index.html` по ссылке имеем 404: https://bmstu-iu9.github.io/utp2018-1-chat/

**Comment by senya-g** [comment]
@Mazdaywik, хорошо. 
Большое спасибо!

**Comment by Mazdaywik** [comment]
Что-то пока нет документации…
