### ISSUE TITLE
Не получается создать беседу

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-1-chat#69]
Зашел с двух аккаунтов(один с обычного другой с инкогнито), попытался создать беседу между этими двумя.Ничего не произошло.
P.S. Если ошибка в моих действиях просьба отписать

**Comment by senya-g** [comment]
Была ошибка в API. При создании диалога один из параметров передавался в БД с неправильным типом данных => происходила ошибка.

Исправлено в a5b22eb737996bcc1012abd66509fd9aae847ad2

В master ветку с исправлением солью после еще парочки исправлений.
