### ISSUE TITLE
Запуск

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-1-chat#72]
После запуска открывается не страница со входом и регистрацией, а непосредственно сам чат.

**Comment by senya-g** [comment]
Поясни.
Такой ситуации не должно возникать. Проверяли на этапе реализации несколько раз. 

Ты до этого авторизировался уже в чате?

Когда пользователь авторизируется, ему в cookie записывается токен сессии. При повторных подключениях авторизация происходит уже по этому токену (сверяется токен у пользователя и токен в БД) и вводить повторно логин и пароль не требуется, если токен валиден и его срок действия не истек.

**Comment by senya-g** [comment]
Если папка с БД не удалялась и/или куки браузера не очищались, то это естественное поведение.

**Comment by Lanaken** [comment]
Да, моя ошибка.

**Comment by senya-g** [comment]
Возможно нам стоило добавить чекбокс при входе «Сохранить сессию»/«Запомнить меня», чтобы этот момент был очевиден, но как-то было не до этого :)
