### ISSUE TITLE
Функция +

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-1-chat#73]
В диалоге функция "+" дает выбрать какой-нибудь файл с жесткого диска пользователя, но при этом не загружает его.

**Comment by senya-g** [comment]
Решили просто отключить эту возможность.
Не находится время.

Если ближайшие 2 дня выпадет возможность, то реализуем.

Коммит, где данная возможность будет недоступна, внесем в `master` до конца дня.
